import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import crypto from 'crypto';

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const uid = searchParams.get('uid');
  const email = searchParams.get('email');
  const token = searchParams.get('token');

  if (!uid || !email || !token) {
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Link de confirmação inválido.")}`);
  }

  // 1. Verify the HMAC token (This proves the link was generated by our server for this specific user)
  const secret = process.env.EMAIL_CONFIRM_SECRET || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!secret) {
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Erro de configuração do servidor.")}`);
  }
  const payload = `${uid}:${email}`;
  const expectedToken = crypto.createHmac('sha256', secret).update(payload).digest('hex');

  if (token !== expectedToken) {
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Link de confirmação corrompido ou inválido.")}`);
  }

  // 2. Token is VALID. We can confirm the email even if the user is not logged in.
  const supabase = await createClient();
  
  // Call the SECURITY DEFINER RPC function to bypass RLS and update the profile
  const { error: updateError } = await supabase.rpc('confirm_user_email', {
    user_uid: uid
  });

  if (updateError) {
    console.error("Erro ao confirmar e-mail via RPC:", updateError);
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Erro interno ao confirmar o e-mail.")}`);
  }

  // 3. Now we check if the user happens to be logged in on this current browser session
  const { data: { user } } = await supabase.auth.getUser();

  // Se o usuário não estiver logado (ou estiver logado em outra conta),
  // redirecionamos para o login avisando que o e-mail FOI confirmado com sucesso.
  if (!user || user.id !== uid) {
    return NextResponse.redirect(`${origin}/login?success=${encodeURIComponent("E-mail confirmado com sucesso! Por favor, faça login para acessar sua conta.")}`);
  }

  // Se estiver logado corretamente, vai direto para o painel.
  return NextResponse.redirect(`${origin}/painel?success=${encodeURIComponent("E-mail confirmado com sucesso!")}`);
}
