import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createClient as createAdminClient } from '@supabase/supabase-js';
import crypto from 'crypto';

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const uid = searchParams.get('uid');
  const email = searchParams.get('email');
  const token = searchParams.get('token');

  if (!uid || !email || !token) {
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Link de confirmação inválido.")}`);
  }

  // 1. Verify the HMAC token (This proves the link was generated by our server for this specific user)
  const secret = process.env.EMAIL_CONFIRM_SECRET || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!secret) {
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Erro de configuração do servidor.")}`);
  }
  const payload = `${uid}:${email}`;
  const expectedToken = crypto.createHmac('sha256', secret).update(payload).digest('hex');

  if (token !== expectedToken) {
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Link de confirmação corrompido ou inválido.")}`);
  }

  // 2. Token is VALID. We can confirm the email even if the user is not logged in.
  // Since the user might not be logged in (e.g. clicked link on mobile email app),
  // we use the Service Role Key to bypass RLS and update the profile.
  const adminClient = createAdminClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  const { error: updateError } = await adminClient
    .from('profiles')
    .update({ email_confirmed_at: new Date().toISOString() })
    .eq('id', uid);

  if (updateError) {
    console.error("Erro ao confirmar e-mail via admin client:", updateError);
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent("Erro interno ao confirmar o e-mail.")}`);
  }

  // 3. Now we check if the user happens to be logged in on this current browser session
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  // Se o usuário não estiver logado (ou estiver logado em outra conta),
  // redirecionamos para o login avisando que o e-mail FOI confirmado com sucesso.
  if (!user || user.id !== uid) {
    return NextResponse.redirect(`${origin}/login?success=${encodeURIComponent("E-mail confirmado com sucesso! Por favor, faça login para acessar sua conta.")}`);
  }

  // Se estiver logado corretamente, vai direto para o painel.
  return NextResponse.redirect(`${origin}/painel?success=${encodeURIComponent("E-mail confirmado com sucesso!")}`);
}
